"""timestameped tasks

Revision ID: 007a920e369c
Revises: 10eeef04580a
Create Date: 2026-03-07 01:16:53.123798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '007a920e369c'
down_revision: Union[str, Sequence[str], None] = '10eeef04580a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('task_assignee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['assignee_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_assignee_id_fkey'), 'user', ['assignee_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
