"""create_tasks projects and history

Revision ID: 10eeef04580a
Revises: 342a1f098ae1
Create Date: 2026-03-06 21:26:17.703273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '10eeef04580a'
down_revision: Union[str, Sequence[str], None] = '342a1f098ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_owner_id'), ['owner_id'], unique=False)

    op.create_table('projectmember',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    with op.batch_alter_table('projectmember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projectmember_user_id'), ['user_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('created', 'in_progress', 'review', 'done', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_project_id'), ['project_id'], unique=False)

    op.create_table('taskstatushistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('created', 'in_progress', 'review', 'done', 'cancelled', name='taskstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('created', 'in_progress', 'review', 'done', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taskstatushistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taskstatushistory_changed_by_user_id'), ['changed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taskstatushistory_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskstatushistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taskstatushistory_task_id'))
        batch_op.drop_index(batch_op.f('ix_taskstatushistory_changed_by_user_id'))

    op.drop_table('taskstatushistory')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_author_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignee_id'))

    op.drop_table('task')
    with op.batch_alter_table('projectmember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projectmember_user_id'))

    op.drop_table('projectmember')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_owner_id'))

    op.drop_table('project')
    # ### end Alembic commands ###
